FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

WORKDIR /home/ubuntu/work

RUN apt-get update && \
    apt-get install -y python3-pip python3-dev python-is-python3 && \
    rm -rf /var/lib/apt/lists/*


RUN apt-get update && \
    apt-get -y install ffmpeg libsm6 libxext6  && \
    rm -rf /var/lib/apt/lists/*

RUN pip install jupyter

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY work/. .
EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
