FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
WORKDIR /develop

RUN apt-get update && \
    apt-get install -y python3-pip python3-dev python-is-python3 && \
    rm -rf /var/lib/apt/lists/*


RUN apt-get update && \
    apt-get -y install ffmpeg libsm6 libxext6  && \
    rm -rf /var/lib/apt/lists/*

    
RUN apt install git git-flow nano -y
# RUN pip install torch torchvision torchaudio torchtext
# RUN pip install pandas xlwt torchsummary torchvision
# RUN pip install pytorch-forecasting


COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt
